In [5]:
import pandas as pd
df = pd.read_csv('../resources/acs2017_county_data.csv')

In [8]:
pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 2.6 MB/s eta 0:00:01
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1
Note: you may need to restart the kernel to use updated packages.

In [6]:
df.head()

,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga County,55036,26899,28137,2.7,75.4,18.9,0.3,...,0.6,1.3,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2
1,1003,Alabama,Baldwin County,203360,99527,103833,4.4,83.1,9.5,0.8,...,0.8,1.1,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5
2,1005,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,...,2.2,1.7,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4
3,1007,Alabama,Bibb County,22580,12251,10329,2.4,74.6,22.0,0.4,...,0.3,1.7,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2
4,1009,Alabama,Blount County,57667,28490,29177,9.0,87.4,1.5,0.3,...,0.4,0.4,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9

In [45]:
df.columns

Index(['CountyId', 'State', 'County', 'TotalPop', 'Men', 'Women', 'Hispanic',
       'White', 'Black', 'Native', 'Asian', 'Pacific', 'VotingAgeCitizen',
       'Income', 'IncomeErr', 'IncomePerCap', 'IncomePerCapErr', 'Poverty',
       'ChildPoverty', 'Professional', 'Service', 'Office', 'Construction',
       'Production', 'Drive', 'Carpool', 'Transit', 'Walk', 'OtherTransp',
       'WorkAtHome', 'MeanCommute', 'Employed', 'PrivateWork', 'PublicWork',
       'SelfEmployed', 'FamilyWork', 'Unemployment'],
      dtype='object')

In [51]:
usda=pd.read_excel('../resources/ruralurbancodes2013.xls')

In [52]:
usda.columns

Index(['FIPS', 'State', 'County_Name', 'Population_2010', 'RUCC_2013',
       'Description'],
      dtype='object')

In [53]:
usda.sample(10)

,FIPS,State,County_Name,Population_2010,RUCC_2013,Description
1527,29089,MO,Howard County,10144,6,"Nonmetro - Urban population of 2,500 to 19,999..."
722,18051,IN,Gibson County,33503,6,"Nonmetro - Urban population of 2,500 to 19,999..."
742,18091,IN,LaPorte County,111467,3,Metro - Counties in metro areas of fewer than ...
1233,26005,MI,Allegan County,111408,4,"Nonmetro - Urban population of 20,000 or more,..."
2620,48195,TX,Hansford County,5613,7,"Nonmetro - Urban population of 2,500 to 19,999..."
85,2188,AK,Northwest Arctic Borough,7523,7,"Nonmetro - Urban population of 2,500 to 19,999..."
2680,48315,TX,Marion County,10546,8,"Nonmetro - Completely rural or less than 2,500..."
2583,48121,TX,Denton County,662614,1,Metro - Counties in metro areas of 1 million p...
3008,54031,WV,Hardy County,14025,6,"Nonmetro - Urban population of 2,500 to 19,999..."
1069,21153,KY,Magoffin County,13333,9,"Nonmetro - Completely rural or less than 2,500..."

In [54]:
usda=usda.groupby('RUCC_2013')[['RUCC_2013','Description']].max()

In [55]:
usofa=pd.merge(df, usda, left_on='CountyId', right_on='FIPS', how='left')
print(usofa.shape)
print(usda.shape)

KeyError: 'FIPS'

In [25]:
usofa.sample(2)

,CountyId,State_x,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,PublicWork,SelfEmployed,FamilyWork,Unemployment,FIPS,State_y,County_Name,Population_2010,RUCC_2013,Description
1786,34025,New Jersey,Monmouth County,627551,305192,322359,10.6,75.4,6.7,0.1,...,13.8,5.3,0.2,6.0,34025.0,NJ,Monmouth County,630380.0,1.0,Metro - Counties in metro areas of 1 million p...
621,17053,Illinois,Ford County,13470,6647,6823,3.0,94.3,0.9,0.4,...,11.0,10.7,0.2,6.6,17053.0,IL,Ford County,14081.0,3.0,Metro - Counties in metro areas of fewer than ...