In [5]:
import pandas as pd
df = pd.read_csv('../resources/acs2017_county_data.csv')

In [8]:
pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 2.6 MB/s eta 0:00:01
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1
Note: you may need to restart the kernel to use updated packages.

In [6]:
df.head()

,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga County,55036,26899,28137,2.7,75.4,18.9,0.3,...,0.6,1.3,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2
1,1003,Alabama,Baldwin County,203360,99527,103833,4.4,83.1,9.5,0.8,...,0.8,1.1,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5
2,1005,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,...,2.2,1.7,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4
3,1007,Alabama,Bibb County,22580,12251,10329,2.4,74.6,22.0,0.4,...,0.3,1.7,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2
4,1009,Alabama,Blount County,57667,28490,29177,9.0,87.4,1.5,0.3,...,0.4,0.4,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9

In [45]:
df.columns

Index(['CountyId', 'State', 'County', 'TotalPop', 'Men', 'Women', 'Hispanic',
       'White', 'Black', 'Native', 'Asian', 'Pacific', 'VotingAgeCitizen',
       'Income', 'IncomeErr', 'IncomePerCap', 'IncomePerCapErr', 'Poverty',
       'ChildPoverty', 'Professional', 'Service', 'Office', 'Construction',
       'Production', 'Drive', 'Carpool', 'Transit', 'Walk', 'OtherTransp',
       'WorkAtHome', 'MeanCommute', 'Employed', 'PrivateWork', 'PublicWork',
       'SelfEmployed', 'FamilyWork', 'Unemployment'],
      dtype='object')

In [56]:
usda=pd.read_excel('../resources/ruralurbancodes2013.xls')

In [57]:
usda.columns

Index(['FIPS', 'State', 'County_Name', 'Population_2010', 'RUCC_2013',
       'Description'],
      dtype='object')

In [58]:
usda.sample(10)

,FIPS,State,County_Name,Population_2010,RUCC_2013,Description
1074,21163,KY,Meade County,28602,3,Metro - Counties in metro areas of fewer than ...
1287,26113,MI,Missaukee County,14849,9,"Nonmetro - Completely rural or less than 2,500..."
1140,22055,LA,Lafayette Parish,221578,2,"Metro - Counties in metro areas of 250,000 to ..."
287,8085,CO,Montrose County,41276,4,"Nonmetro - Urban population of 20,000 or more,..."
3036,54087,WV,Roane County,14926,6,"Nonmetro - Urban population of 2,500 to 19,999..."
3150,72015,PR,Arroyo Municipio,19575,3,Metro - Counties in metro areas of fewer than ...
2139,40017,OK,Canadian County,115541,1,Metro - Counties in metro areas of 1 million p...
269,8049,CO,Grand County,14843,7,"Nonmetro - Urban population of 2,500 to 19,999..."
1367,27107,MN,Norman County,6852,8,"Nonmetro - Completely rural or less than 2,500..."
34,1069,AL,Houston County,101547,3,Metro - Counties in metro areas of fewer than ...

In [59]:
usda.groupby('RUCC_2013')[['RUCC_2013','Description',]].max()

           RUCC_2013                                        Description
RUCC_2013
1                  1  Metro - Counties in metro areas of 1 million p...
2                  2  Metro - Counties in metro areas of 250,000 to ...
3                  3  Metro - Counties in metro areas of fewer than ...
4                  4  Nonmetro - Urban population of 20,000 or more,...
5                  5  Nonmetro - Urban population of 20,000 or more,...
6                  6  Nonmetro - Urban population of 2,500 to 19,999...
7                  7  Nonmetro - Urban population of 2,500 to 19,999...
8                  8  Nonmetro - Completely rural or less than 2,500...
9                  9  Nonmetro - Completely rural or less than 2,500...

In [60]:
usofa=pd.merge(df, usda, left_on='CountyId', right_on='FIPS', how='left')
print(usofa.shape)
print(usda.shape)

(3220, 43)
(3221, 6)

In [61]:
usofa.sample(2)

,CountyId,State_x,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,PublicWork,SelfEmployed,FamilyWork,Unemployment,FIPS,State_y,County_Name,Population_2010,RUCC_2013,Description
3000,54017,West Virginia,Doddridge County,8570,4641,3929,0.4,95.7,1.4,0.1,...,18.5,6.4,0.0,6.5,54017.0,WV,Doddridge County,8202.0,9.0,"Nonmetro - Completely rural or less than 2,500..."
2377,46033,South Dakota,Custer County,8519,4275,4244,3.0,90.6,0.2,3.6,...,18.3,14.0,1.0,4.0,46033.0,SD,Custer County,8216.0,3.0,Metro - Counties in metro areas of fewer than ...

In [63]:
usofa.columns

Index(['CountyId', 'State_x', 'County', 'TotalPop', 'Men', 'Women', 'Hispanic',
       'White', 'Black', 'Native', 'Asian', 'Pacific', 'VotingAgeCitizen',
       'Income', 'IncomeErr', 'IncomePerCap', 'IncomePerCapErr', 'Poverty',
       'ChildPoverty', 'Professional', 'Service', 'Office', 'Construction',
       'Production', 'Drive', 'Carpool', 'Transit', 'Walk', 'OtherTransp',
       'WorkAtHome', 'MeanCommute', 'Employed', 'PrivateWork', 'PublicWork',
       'SelfEmployed', 'FamilyWork', 'Unemployment', 'FIPS', 'State_y',
       'County_Name', 'Population_2010', 'RUCC_2013', 'Description'],
      dtype='object')